### ISSUE TITLE
Curious behaviours on travis of hrpsys_ros_bridge_tutorials

### ISSUE THREAD

**Issue by snozawa** [jsk-ros-pkg/jsk_travis#129]
There are curious behaviours on travis of hrpsys_ros_bridge_tutorials.

1. rostest fails but travis says succes.
In https://travis-ci.org/start-jsk/rtmros_tutorials/builds/77014742, 
rostest fails but travis says succes.

2. Could not resolve `hrpsys_ros_bridge_tutorials`.
On rostest programs in `hrpsys_ros_bridge_tutorials/test`, 
they cannot resolve package name `hrpsys_ros_bridge_tutorials`(https://s3.amazonaws.com/archive.travis-ci.org/jobs/77014750/log.txt):
```
]2;[build] 1/5[35m[1mScanning dependencies of target _run_tests_hrpsys_ros_bridge_tutorials_rostest_test_samplerobot_hrpsys-ros-bridge_test.launch [0m[0m
]2;[build] 1/5[0m-- run_tests.py: execute commands                                               [0m[0m
]2;[build] 1/5  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials --package=hrpsys_ros_bridge_tutorials --results-filename test_samplerobot_hrpsys-ros-bridge_test.xml /home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/test/samplerobot_hrpsys-ros-bridge_test.launch [0m[0m
]2;[build] 1/5]2;[build] 1/5]2;[build] 1/5... logging to /home/travis/.ros/log/rostest-testing-worker-linux-08b40318-2-25201-linux-9-77014750-4825.log [0m[0m
]2;[build] 1/5]2;[build] 1/5]2;[build] 1/5Traceback (most recent call last):                                              [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest", line 53, in <module> [0m[0m
]2;[build] 1/5    rostestmain()                                                               [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain [0m[0m
]2;[build] 1/5    _main()                                                                     [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_main.py", line 142, in rostestmain [0m[0m
]2;[build] 1/5    testCase = rostest.runner.createUnitTest(pkg, test_file)                    [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 227, in createUnitTest [0m[0m
]2;[build] 1/5    config = roslaunch.parent.load_config_default([test_file], _DEFAULT_TEST_PORT) [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/config.py", line 428, in load_config_default [0m[0m
]2;[build] 1/5    loader.load(f, config, verbose=verbose)                                     [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 698, in load [0m[0m
]2;[build] 1/5    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose) [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 670, in _load_launch [0m[0m
]2;[build] 1/5    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose) [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _recurse_load [0m[0m
]2;[build] 1/5    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose) [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call [0m[0m
]2;[build] 1/5    return f(*args, **kwds)                                                     [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 553, in _include_tag [0m[0m
]2;[build] 1/5    inc_filename = self.resolve_args(tag.attributes['file'].value, context)     [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 159, in resolve_args [0m[0m
]2;[build] 1/5    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon) [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 299, in resolve_args [0m[0m
]2;[build] 1/5    resolved = _resolve_args(resolved, context, resolve_anon, commands)         [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in _resolve_args [0m[0m
]2;[build] 1/5    resolved = commands[command](resolved, a, args, context)                    [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 137, in _find [0m[0m
]2;[build] 1/5    return _find_executable(resolve_without_path, a, [args[0], path], context)  [0m[0m
]2;[build] 1/5  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 173, in _find_executable [0m[0m
]2;[build] 1/5    full_path = _get_executable_path(rp.get_path(args[0]), path)                [0m[0m
]2;[build] 1/5  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path [0m[0m
]2;[build] 1/5    raise ResourceNotFound(name, ros_paths=self._ros_paths)                     [0m[0m
]2;[build] 1/5rospkg.common.ResourceNotFound: hrpsys_ros_bridge_tutorials                     [0m[0m
]2;[build] 1/5ROS path [0]=/opt/ros/hydro/share/ros                                           [0m[0m
]2;[build] 1/5ROS path [1]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hironx_tutorial [0m[0m
]2;[build] 1/5ROS path [2]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hironx_tutorial [0m[0m
]2;[build] 1/5ROS path [3]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_tutorials [0m[0m
]2;[build] 1/5ROS path [4]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/openhrp3_tutorials [0m[0m
]2;[build] 1/5ROS path [5]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_gazebo_tutorials [0m[0m
]2;[build] 1/5ROS path [6]=/opt/ros/hydro/share                                               [0m[0m
]2;[build] 1/5ROS path [7]=/opt/ros/hydro/stacks                                              [0m[0m
]2;[build] 1/5-- run_tests.py: verify result "/home/travis/ros/ws_rtmros_tutorials/build/hrpsys_ros_bridge_tutorials/test_results/hrpsys_ros_bridge_tutorials/rostest-test_samplerobot_hrpsys-ros-bridge_test.xml" [0m[0m
```

**Comment by k-okada** [comment]
> rostest fails but travis says succes.
> In https://travis-ci.org/start-jsk/rtmros_tutorials/builds/77014742,
> rostest fails but travis says succes.

That's known issue and workaround is proposed in
https://github.com/jsk-ros-pkg/jsk_travis/pull/108,
https://github.com/start-jsk/2014-semi/issues/816#issuecomment-118296963

> Could not resolve hrpsys_ros_bridge_tutorials.
> On rostest programs in hrpsys_ros_bridge_tutorials/test,
> they cannot resolve package name hrpsys_ros_bridge_tutorials(https://s3.amazonaws.com/archive.travis-ci.org/jobs/77014750/log.txt):

thats may another known issue (https://github.com/ros/catkin/pull/671)
which catkin write `.catkin` file simultaneously and delete another
one.
(note that list of ROS_PACKAGE_PATH is written to the devel/.catkin
file), we have to run travis several times to solve this.
but before that I'd recommend you to remove
```
 ]2;[build] 2/5 [ [36mhrpsys_ros_bridge_tutorials [0m]   Could not
find module Findhrpsys_ros_bridge_tutorials.cmake or a [0m  [0m [0m

```
remove hrpsys_ros_bridge_tutorials from hrpsys_ros_bridge_tutorial/package.xml ?
```
 ]2;[build] 1/5 roslaunch.core.RLException: Invalid <arg> tag:
hrpsys_ros_bridge_tutorials       [0m [0m

```
errors



--
◉ Kei Okada

**Comment by snozawa** [comment]
> That's known issue and workaround is proposed in
> https://github.com/jsk-ros-pkg/jsk_travis/pull/108,
> https://github.com/start-jsk/2014-semi/issues/816#issuecomment-118296963

I see, thank you for your announcement.


> thats may another known issue (https://github.com/ros/catkin/pull/671) which catkin write `.catkin` file > simultaneously and delete another one. (note that list of ROS_PACKAGE_PATH is written to the > devel/.catkin file), we have to run travis several times to solve this. but before that I'd recommend you to remove

For the problem 2, is this problem related with compile with `-j1` or something?

**Comment by k-okada** [comment]
The problem is due to catkin try to bild several packages at same time, so
compile with -p1 may solve this problem
```
  -p PARALLEL_JOBS, --parallel-packages PARALLEL_JOBS, --parallel-jobs
PARALLEL_JOBS, --parallel PARALLEL_JOBS
                        Maximum number of packages which could be built in
                        parallel (default is cpu count)
  -j JOBS, --jobs JOBS  Limit parallel job count through the internal GNU
make
                        job server. default is cpu count
``@

--
◉ Kei Okada


On Wed, Aug 26, 2015 at 2:07 PM, Shunichi Nozawa <notifications@github.com>
wrote:

> That's known issue and workaround is proposed in
> #108 <https://github.com/jsk-ros-pkg/jsk_travis/pull/108>,
> start-jsk/2014-semi#816 (comment)
> <https://github.com/start-jsk/2014-semi/issues/816#issuecomment-118296963>
>
> I see, thank you for your announcement.
>
> thats may another known issue (ros/catkin#671
> <https://github.com/ros/catkin/pull/671>) which catkin write .catkin file
> > simultaneously and delete another one. (note that list of
> ROS_PACKAGE_PATH is written to the > devel/.catkin file), we have to run
> travis several times to solve this. but before that I'd recommend you to
> remove
>
> For the problem 2, is this problem related with compile with -j1 or
> something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/issues/129#issuecomment-134832661>
> .
>

**Comment by snozawa** [comment]
Thanks, I see.
(I got the difference between `-p1` and `-j1` on catkin usage)

**Comment by wkentaro** [comment]
Fixed?
