### ISSUE TITLE
need to remove old files in jenkins automatically

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#16]
また容量足りなくなっています。

どこを削除すればよいのでしょうか?

**Comment by garaemon** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/computer/(master)/executors/0/causeOfDeath

またこの問題です

**Comment by garaemon** [comment]
定期的にファイルを削除するcronスクリプトがほしいです

**Comment by k-okada** [comment]
jenkins側の設定でけしているんだけどなぁ．

--
◉ Kei Okada

**Comment by k-okada** [comment]
信じられないけど，.xsession-errorsが３００Gありました．．．．
root@jenkins:/home/lokada# ls -hal .xsession-errors*
-rw------- 1 lokada lokada 359G  1月 19 11:03 .xsession-errors
-rw------- 1 lokada lokada  34K  1月  5 23:16 .xsession-errors.old


--
◉ Kei Okada


2015-01-19 10:51 GMT+09:00 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>:

**Comment by garaemon** [comment]
x上げて落ちる、というのが何度もあったという事でしょうか。eus?

◉  ryohei

**Comment by garaemon** [comment]
まだ動きませんが、何が必要ですか?

**Comment by garaemon** [comment]
まだsda1が402G使用中に見えますが、消していませんか?
```
lueda@jenkins:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       424G  402G     0 100% /
```

**Comment by garaemon** [comment]
今ってジョブが溜まってなかなか消化されていない?

**Comment by garaemon** [comment]
again
```
lueda@jenkins:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       424G  404G     0 100% /
udev             63G  4.0K   63G   1% /dev
tmpfs            13G  892K   13G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none             63G  8.8M   63G   1% /run/shm
cgroup           63G     0   63G   0% /sys/fs/cgroup
/dev/sdc1       550G  143G  379G  28% /export/data2
/dev/sdd1       550G  483G   40G  93% /export/data3
/dev/sdb1       550G   83G  440G  16% /export/data1
/dev/loop0       31M  396K   29M   2% /tmp/mount.57608

```

**Comment by garaemon** [comment]
```
lueda@jenkins:/home/lokada$ du -h -d 0 2>/dev/null
267G	.
lueda@jenkins:/home/lokada$ ls -alh
-rw-------  1 lokada lokada 267G Feb 14 13:00 .xsession-errors
```

**Comment by garaemon** [comment]
```
root@jenkins:/home/lokada# rm .xsession-errors
```
should be fixed

**Comment by garaemon** [comment]
ファイルを消して、jenkinsのnodeをrestartするだけでは不十分ですか?

**Comment by garaemon** [comment]
.xsession-errorsを開いているプロセスがまだ少しいるようです
```
# lsof | grep xsession
lsof: WARNING: can't stat() fuse.gvfs-fuse-daemon file system /home/lokada/.gvfs
      Output information may be incomplete.
gnome-ses  2869      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
gnome-set  3762      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
metacity   4486      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
unity-2d-  4597      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
unity-2d-  4598      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
bluetooth  4606      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
nm-applet  4607      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
vino-serv  4610      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
polkit-gn  4611      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
gnome-fal  4612      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
nautilus   4617      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
gdu-notif  4924      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
telepathy  5012      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
gnome-scr  5049      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
update-no  5096      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
gnome-ter  5289      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)
deja-dup-  7644      lokada    2w      REG                8,1 285974835200    7733266 /home/lokada/.xsession-errors (deleted)

```

**Comment by k-okada** [comment]
ok, i restart xserver and redirect .xsesison-errors to /dev/null

--
◉ Kei Okada

**Comment by garaemon** [comment]
:+1:

**Comment by garaemon** [comment]
again

```
java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
	at java.io.BufferedWriter.close(BufferedWriter.java:266)
	at hudson.util.AtomicFileWriter.close(AtomicFileWriter.java:95)
	at hudson.util.AtomicFileWriter.commit(AtomicFileWriter.java:110)
	at hudson.util.TextFile.write(TextFile.java:121)
	at hudson.model.Job.saveNextBuildNumber(Job.java:290)
	at hudson.model.Job.assignBuildNumber(Job.java:348)
	at hudson.model.Run.<init>(Run.java:279)
	at hudson.model.AbstractBuild.<init>(AbstractBuild.java:170)
	at hudson.model.Build.<init>(Build.java:92)
	at hudson.model.FreeStyleBuild.<init>(FreeStyleBuild.java:34)
	at sun.reflect.GeneratedConstructorAccessor129.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:177)
	at hudson.model.AbstractProject.newBuild(AbstractProject.java:1006)
	at hudson.model.AbstractProject.createExecutable(AbstractProject.java:1205)
	at hudson.model.AbstractProject.createExecutable(AbstractProject.java:144)
	at hudson.model.Executor.run(Executor.java:213)
```

**Comment by garaemon** [comment]
no room in hdd

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       424G  404G     0 100% /
udev             63G  4.0K   63G   1% /dev
tmpfs            13G  968K   13G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none             63G   15M   63G   1% /run/shm
cgroup           63G     0   63G   0% /sys/fs/cgroup
/dev/sdb1       550G  127G  395G  25% /export/data1
/dev/sdc1       550G  144G  378G  28% /export/data2
/dev/sdd1       550G  483G   40G  93% /export/data3
```
