### ISSUE TITLE
Error related to the progressbar in Travis

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#280]
```
next build number is 1624
wait for trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-false-true 1624
start building, wait for result....
Traceback (most recent call last):
  File "./.travis/travis_jenkins.py", line 394, in <module>
    result = wait_for_finished(job_name, build_number)
  File "./.travis/travis_jenkins.py", line 248, in wait_for_finished
    pbar.update(min(progress, 1))  # in case of longer than estimatation
  File "/home/travis/.local/lib/python2.7/site-packages/progressbar/bar.py", line 465, in update
    self.start()
  File "/home/travis/.local/lib/python2.7/site-packages/progressbar/bar.py", line 539, in start
    self.update(self.min_value, force=True)
  File "/home/travis/.local/lib/python2.7/site-packages/progressbar/bar.py", line 496, in update
    StdRedirectMixin.update(self, value=value)
  File "/home/travis/.local/lib/python2.7/site-packages/progressbar/bar.py", line 119, in update
    if self.redirect_stdout and sys.stdout.tell():
IOError: [Errno 29] Illegal seek
```

**Comment by wkentaro** [comment]
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/140006534

**Comment by k-okada** [comment]
Is this problem in jenkins? because jenkins does not have `/home/travis/`

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Oh, I misunderstood. It is in Travis.
